# Generated by Django 4.2.5 on 2024-11-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sensors', '0001_initial'), ('sensors', '0002_alter_sensoracquisition_sensor_acquisitions'), ('sensors', '0003_alter_sensoracquisition_platform_id')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAcquisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_id', models.CharField(max_length=255)),
                ('fetch_datetime', models.DateTimeField()),
                ('datetime_received', models.DateTimeField()),
                ('sensor_acquisitions', models.TextField()),
            ],
        ),
    ]
