# Generated by Django 4.2.5 on 2024-11-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAcquisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_id', models.CharField(max_length=100)),
                ('fetch_datetime', models.DateTimeField()),
                ('datetime_received', models.DateTimeField()),
                ('sensor_acquisitions', models.FloatField()),
            ],
        ),
    ]
