# Generated by Django 4.2.5 on 2024-11-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensoracquisition_sensor_acquisitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoracquisition',
            name='platform_id',
            field=models.CharField(max_length=255),
        ),
    ]
